### ISSUE TITLE
New Heroku instance 404s when trying (causes hook to fail)

### ISSUE THREAD

**Issue by snario** [opbeat/slack-hook#3]
I click the deploy to Heroku button, make a new instance with the SLACK_URL, and then copy the resulting url `http://whatevr.herokuapp.com` and paste it into OpBeat. I then do any random activity and I get `	Disabled until Jan. 21, 2015, 5:09 a.m., last response code: 404.`.

**Comment by snario** [comment]
Nevermind, Heroku has a bug where the build does not display the `/new-activity` ending of the URL.

**Comment by roncohen** [comment]
Maybe we can make the full url more visible. @vanjacosic ?

Glad you got it working though. Let me know if you run into any issues!

**Comment by vanjacosic** [comment]
@roncohen I'm not sure how we can address it if it's on Herokus end.

I just tried setting up a fresh app and when I go to `/setup` via the build link, the page shows the full url including `/new-activity` at the end. So seems to work fine now.

But let me know if there's something concrete we can do to make it better.

**Comment by snario** [comment]
I would just show in your README that `/new-activity` needs to be added to the end of the domain name for people that experience weird issues like this.

**Comment by vanjacosic** [comment]
Good call - I have just updated it.

Thanks again @snario for pointing this out! :)
