### ISSUE TITLE
'None' shown for company name when creating a new app

### ISSUE THREAD

**Issue by AndreasBackx** [opbeat/slack-hook#5]
When creating a new app, the following is sent to the Slack channel:

```
OpbeatBOT [18:12] 
Appname: <None|Appname>
----------------
App Appname created
```

I guess that 'None' needs to be the name of the company? 

Edit: I'm no longer using the slack-hook for Heroku since Opbeat now offers it via the web app.

**Comment by roncohen** [comment]
Hey Andreas. Thank you for this. We're deprecating the project because, as you mentioned, Opbeat now has built-in support for Slack and thus is no longer needed.
